Controllers/LibrariesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using StudentELibrary.Models;

namespace StudentELibrary.Controllers
{
    [Authorize]
    public class LibrariesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Details()
        {
            ResourceSearchModel model = new ResourceSearchModel();

            model.SubjectFilters = new List<SubjectFilter>();
            var subjects = db.Subjects.ToList();
            subjects.Sort((subject1, subject2) => subject1.Name.CompareTo(subject2.Name));
            subjects.ForEach(subject => model.SubjectFilters.Add(new SubjectFilter() { Subject = subject, IsChecked = false }));

            model.SemesterFilters = new List<SemesterFilter>()
            {
                new SemesterFilter()
                {
                    Semester = SemesterFilter.SemesterType.Autumn,
                    IsChecked = false
                },
                new SemesterFilter()
                {
                    Semester = SemesterFilter.SemesterType.Spring,
                    IsChecked = false
                }
            };

            model.YearFilters = new List<YearFilter>()
            {
                new YearFilter()
                {
                    Year = YearFilter.YearType.First,
                    IsChecked = false
                },
                new YearFilter()
                {
                    Year = YearFilter.YearType.Second,
                    IsChecked = false
                },
                new YearFilter()
                {
                    Year = YearFilter.YearType.Third,
                    IsChecked = false
                },
                new YearFilter()
                {
                    Year = YearFilter.YearType.Fourth,
                    IsChecked = false
                }
            };

            model.StudentProgrammeFilters = new List<StudentProgrammeFilter>();
            db.StudyProgrammes.ToList().ForEach(studyProgramme => model.StudentProgrammeFilters.Add(new StudentProgrammeFilter() { StudyProgramme = studyProgramme, IsChecked = false }));

            List<SelectListItem> list = new List<SelectListItem>()
            {
                new SelectListItem() { Text = "Наслов", Value = "Title" },
                new SelectListItem() { Text = "Автор", Value = "Author" },
                new SelectListItem() { Text = "Јазик", Value = "Language" },
                new SelectListItem() { Text = "Предмет", Value = "Subject" }
            };
            model.SortByOptions = new SelectList(list, "Value", "Text");

            model.Ascending = true;

            model.TotalPages = (int)Math.Ceiling((decimal)db.Resources.Count() / model.PageSize);

            return View(model);
        }

        [HttpPost]
        public ActionResult RenderResources(ResourceSearchModel model)
        {
            List<Resource> resources = GetCurrentUser().Library.Resources;

            if (model.SubjectFilters != null)
            {
                List<int> selectedSubjectsIds = model.SubjectFilters.Where(filter => filter.IsChecked)
                .Select(filter => filter.Subject.Id)
                .ToList();

                if (selectedSubjectsIds.Count > 0)
                    resources = resources.Where(resource => selectedSubjectsIds.Contains(resource.Subject.Id)).ToList();
            }

            List<int> selectedSemesters = model.SemesterFilters.Where(filter => filter.IsChecked)
                .Select(filter => (int)filter.Semester + 1)
                .ToList();

            if (selectedSemesters.Count > 0)
                resources = resources.Where(resource => selectedSemesters.Contains(resource.Subject.Semester)).ToList();

            List<int> selectedYears = model.YearFilters.Where(filter => filter.IsChecked)
                .Select(filter => (int)filter.Year + 1)
                .ToList();
            if (selectedYears.Count > 0)
                resources = resources.Where(resource => selectedYears.Contains(resource.Subject.Year)).ToList();

            if (model.StudentProgrammeFilters != null)
            {
                List<int> selectedStudyProgrammeIds = model.StudentProgrammeFilters.Where(filter => filter.IsChecked)
                .Select(filter => filter.StudyProgramme.Id)
                .ToList();
                if (selectedStudyProgrammeIds.Count > 0)
                    resources = resources.Where(resource => selectedStudyProgrammeIds.Contains(resource.Subject.StudyProgramme.Id)).ToList();
            }

            if (!String.IsNullOrEmpty(model.SearchString))
            {
                model.SearchString = model.SearchString.ToLower();
                resources = resources.Where(resource =>
                {
                    return resource.Title.ToLower().Contains(model.SearchString) ||
                    resource.Author.ToLower().Contains(model.SearchString) ||
                    resource.Subject.Name.ToLower().Contains(model.SearchString);
                }).ToList();
            }

            if (model.SelectedSortByOption == "Title")
                resources.Sort((resource1, resource2) =>
                {
                    if (model.Ascending)
                        return resource1.Title.CompareTo(resource2.Title);
                    else
                        return resource2.Title.CompareTo(resource1.Title);
                });
            else if (model.SelectedSortByOption == "Author")
                resources.Sort((resource1, resource2) =>
                {
                    if (model.Ascending)
                        return resource1.Author.CompareTo(resource2.Author);
                    else
                        return resource2.Author.CompareTo(resource1.Author);
                });
            else if (model.SelectedSortByOption == "Language")
                resources.Sort((resource1, resource2) =>
                {
                    if (model.Ascending)
                        return resource1.Language.CompareTo(resource2.Language);
                    else
                        return resource2.Language.CompareTo(resource1.Language);
                });
            else if (model.SelectedSortByOption == "Subject")
                resources.Sort((resource1, resource2) =>
                {
                    if (model.Ascending)
                        return resource1.Subject.Name.CompareTo(resource2.Subject.Name);
                    else
                        return resource2.Subject.Name.CompareTo(resource1.Subject.Name);
                });

            model.TotalPages = (int)Math.Ceiling((decimal)resources.Count / model.PageSize);

            int count = (model.PageSize < resources.Count) ? model.PageSize : resources.Count;
            model.Resources = resources.Skip(model.PageSize * (model.PageNumber - 1)).Take(count).ToList();

            if (model.Resources.Count == 0 && model.PageNumber > 0)
            {
                --model.PageNumber;
                count = (model.PageSize < resources.Count) ? model.PageSize : resources.Count;
                model.Resources = resources.Skip(model.PageSize * (model.PageNumber - 1)).Take(count).ToList();
            }

            return PartialView(model);
        }

        private ApplicationUser GetCurrentUser()
        {
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser applicationUser = db.Users.FirstOrDefault(user => user.Id == currentUserId);
            return applicationUser;
        }

        public ActionResult AddToLibrary(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Resource resource = db.Resources.Find(id);
            if (resource == null)
                return HttpNotFound();

            ApplicationUser applicationUser = GetCurrentUser();

            applicationUser.Library.Resources.Add(resource);
            db.SaveChanges();

            return RedirectToAction("Details");
        }

        public ActionResult RemoveFromLibrary(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Resource resource = db.Resources.Find(id);
            if (resource == null)
                return HttpNotFound();

            ApplicationUser applicationUser = GetCurrentUser();

            applicationUser.Library.Resources.Remove(resource);
            db.SaveChanges();

            return RedirectToAction("Details");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentELibrary.Models;

namespace StudentELibrary.Controllers
{
    [Authorize(Roles = "Administrator,Teacher")]
    public class SubjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Subjects
        public ActionResult Index()
        {
            return View(db.Subjects.ToList());
        }

        // GET: Subjects/Create
        public ActionResult Create()
        {
            Subject subject = new Subject();
            List<SelectListItem> list = db.StudyProgrammes.Select(studyProgramme => new SelectListItem() { Text = studyProgramme.Name, Value = studyProgramme.Id.ToString() }).ToList();
            subject.AllStudyProgrammes = new SelectList(list, "Value", "Text");

            return View(subject);
        }

        // POST: Subjects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Semester,Year,StudyProgrammeId")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Subjects.Add(subject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            List<SelectListItem> list = db.StudyProgrammes.Select(studyProgramme => new SelectListItem() { Text = studyProgramme.Name, Value = studyProgramme.Id.ToString() }).ToList();
            subject.AllStudyProgrammes = new SelectList(list, "Value", "Text");

            return View(subject);
        }

        // GET: Subjects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }

            List<SelectListItem> list = db.StudyProgrammes.Select(studyProgramme => new SelectListItem() { Text = studyProgramme.Name, Value = studyProgramme.Id.ToString() }).ToList();
            subject.AllStudyProgrammes = new SelectList(list, "Value", "Text");

            return View(subject);
        }

        // POST: Subjects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Semester,Year,StudyProgrammeId")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            List<SelectListItem> list = db.StudyProgrammes.Select(studyProgramme => new SelectListItem() { Text = studyProgramme.Name, Value = studyProgramme.Id.ToString() }).ToList();
            subject.AllStudyProgrammes = new SelectList(list, "Value", "Text");

            return View(subject);
        }

        // GET: Subjects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Subject subject = db.Subjects.Find(id);
            db.Subjects.Remove(subject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Студентска е-библиотека</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Styles", false)

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,600;1,400&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/a0e379122a.js" crossorigin="anonymous"></script>

    <link rel="icon" type="image/x-icon" href="~/Content/Images/book-solid.svg">

    <style>
        html {
            overflow: auto;
        }

        body {
            font-family: Montserrat !important;
        }

        html, body {
            overflow: visible !important;
        }

        /* Scrollbar Styling */
        ::-webkit-scrollbar {
            width: 5px;
            background-color: #2d50ba;
        }

        ::-webkit-scrollbar-track {
            background-color: #a8d3f6;
        }

        ::-webkit-scrollbar-thumb {
            background: #5c7ad1;
        }

        .nav-link {
            color: #2158b0 !important;
        }

        footer {
            color: #2158b0;
        }

        ::-moz-selection {
            color: #8951b5;
            background: #d4bfdf;
        }

        ::selection {
            color: #8951b5;
            background: #d4bfdf;
        }
    </style>


</head>
<body>

    <div id="main-wrapper">
        <header>
            <nav class="navbar navbar-expand-xl navbar-light bg-light" style="background-color: #d4e8ff !important; ">
                <div class="container">
                    <a class="navbar-brand text-uppercase" href="/" style="font-size: large;"><strong style="color: #2158b0; ">Студентска</strong> <strong style="color: #2158b0; ">е-библиотека</strong></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                @Html.ActionLink("Почетна", "Index", "Home", new { }, htmlAttributes: new { @class = "nav-link active" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Ресурси", "Index", "Resources", new { }, htmlAttributes: new { @class = "nav-link" })
                            </li>
                            @if (User.IsInRole("Administrator") || User.IsInRole("Teacher"))
                            {
                                <li class="nav-item">
                                    @Html.ActionLink("Предмети", "Index", "Subjects", new { }, htmlAttributes: new { @class = "nav-link" })
                                </li>
                            }
                            @if (Request.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    @Html.ActionLink("Библиотека", "Details", "Libraries", new { }, htmlAttributes: new { @class = "nav-link" })
                                </li>
                            }
                            @if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item">
                                    @Html.ActionLink("Улоги", "AddToRole", "Account", new { }, htmlAttributes: new { @class = "nav-link" })
                                </li>
                            }
                        </ul>
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </nav>
        </header>
        <main class="row align-items-center m-0 p-0">
            <div class="col body-content m-0 p-0">
                <div class="container p-0">
                    @RenderBody()
                </div>
            </div>
        </main>
        <footer class="bg-light py-3 mt-3" style="background-color: #d4e8ff !important; ">
            <div class="container">
                <div class="row justify-content-center align-items-center">
                    <div class="col-6 col-md-6 col-lg-3 text-center mb-3 mb-md-0">
                        <img class="img-fluid w-75" src="~/Content/Images/footer-img.jpg" />
                    </div>
                    <div class="col-12 col-md-6 col-lg-4 d-flex flex-column justify-content-around">
                        <div class="ms-3">
                            <h6 class="text-uppercase text-center text-lg-start"><strong style="color: #2158b0; ">Студентска</strong> <strong style="color: #2158b0; ">е-библиотека</strong></h6>
                            <p class="mb-0 text-center text-lg-start">Нашата цел е да го олесниме пристапот на студентите до материјали за учење во електронска форма во време на с&egrave; поголема дигитализација.</p>
                        </div>
                    </div>
                    <div class="col-lg-2 col-6 d-none d-lg-flex flex-column justify-content-around">
                        <ul class="navbar-nav text-center">
                            <li>@Html.ActionLink("Почетна", "Index", "Home", new { }, htmlAttributes: new { @class = "active" })</li>
                            <li>@Html.ActionLink("Ресурси", "Index", "Resources", new { }, htmlAttributes: new { @class = "" })</li>
                            @if (User.IsInRole("Administrator") || User.IsInRole("Teacher"))
                            {
                                <li>
                                    @Html.ActionLink("Предмети", "Index", "Subjects", new { }, htmlAttributes: new { @class = "" })
                                </li>
                            }
                            @if (Request.IsAuthenticated)
                            {
                                <li>
                                    @Html.ActionLink("Библиотека", "Details", "Libraries", new { }, htmlAttributes: new { @class = "" })
                                </li>
                            }
                            @if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item">
                                    @Html.ActionLink("Улоги", "AddToRole", "Account", new { }, htmlAttributes: new { @class = "" })
                                </li>
                            }
                        </ul>
                    </div>
                    <div class="col-lg-3 col-8 d-flex flex-column justify-content-around">
                        <div class="small text-center my-3">Организирајте ги достапните ресурси според вашите потреби.</div>
                        <div class="d-flex justify-content-around my-3">
                            @if (Request.IsAuthenticated)
                            {
                                <a href="/Libraries/Details" class="text-decoration-none">
                                    <div>
                                        <div class="text-center">
                                            <i class="fa-solid fa-book-open"></i>
                                        </div>
                                        <div class="text-center small mx-1 text-uppercase">Библиотека</div>
                                    </div>
                                </a>
                            }
                            else
                            {
                                <a href="/Account/Register" id="registerLink" class="text-decoration-none">
                                    <div>
                                        <div class="text-center">
                                            <i class="fa-solid fa-user-plus"></i>
                                        </div>
                                        <div class="text-center small mx-1">Регистрирај се</div>
                                    </div>
                                </a>
                                <a href="/Account/Login" id="loginLink" class="text-decoration-none">
                                    <div>
                                        <div class="text-center">
                                            <i class="fa-solid fa-arrow-right-to-bracket"></i>
                                        </div>
                                        <div class="text-center small mx-1">Најави се</div>
                                    </div>
                                </a>
                            }
                        </div>
                    </div>
                </div>
                <hr />
                <p class="copyright m-0">
                    &copy; Copyright 2022. All rights reserved.
                    <a class="d-block d-sm-inline" href="https://peshevskidimitar.github.io/">Димитар Пешевски</a>
                </p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/js")
    @RenderSection("scripts", required: false)
</body>
</html>