Controllers/HomeController.cs
using StudentELibrary.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentELibrary.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            var resources = db.Resources.OrderBy(resource => resource.DatePublished)
                .Take(8)
                .ToList();
            return View(resources);
        }
    }
}

Controllers/ResourcesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentELibrary.Models;

namespace StudentELibrary.Controllers
{
    [Authorize]
    public class ResourcesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Resources
        [AllowAnonymous]
        public ActionResult Index()
        {
            ResourceSearchModel model = new ResourceSearchModel();

            model.SubjectFilters = new List<SubjectFilter>();
            var subjects = db.Subjects.ToList();
            subjects.Sort((subject1, subject2) => subject1.Name.CompareTo(subject2.Name));
            subjects.ForEach(subject => model.SubjectFilters.Add(new SubjectFilter() { Subject = subject, IsChecked = false }));

            model.SemesterFilters = new List<SemesterFilter>()
            {
                new SemesterFilter()
                {
                    Semester = SemesterFilter.SemesterType.Autumn,
                    IsChecked = false
                },
                new SemesterFilter()
                {
                    Semester = SemesterFilter.SemesterType.Spring,
                    IsChecked = false
                }
            };

            model.YearFilters = new List<YearFilter>()
            {
                new YearFilter()
                {
                    Year = YearFilter.YearType.First,
                    IsChecked = false
                },
                new YearFilter()
                {
                    Year = YearFilter.YearType.Second,
                    IsChecked = false
                },
                new YearFilter()
                {
                    Year = YearFilter.YearType.Third,
                    IsChecked = false
                },
                new YearFilter()
                {
                    Year = YearFilter.YearType.Fourth,
                    IsChecked = false
                }
            };

            model.StudentProgrammeFilters = new List<StudentProgrammeFilter>();
            db.StudyProgrammes.ToList().ForEach(studyProgramme => model.StudentProgrammeFilters.Add(new StudentProgrammeFilter() { StudyProgramme = studyProgramme, IsChecked = false }));

            List<SelectListItem> list = new List<SelectListItem>()
            {
                new SelectListItem() { Text = "Наслов", Value = "Title" },
                new SelectListItem() { Text = "Автор", Value = "Author" },
                new SelectListItem() { Text = "Јазик", Value = "Language" },
                new SelectListItem() { Text = "Предмет", Value = "Subject" }
            };
            model.SortByOptions = new SelectList(list, "Value", "Text");

            model.Ascending = true;

            model.TotalPages = (int)Math.Ceiling((decimal)db.Resources.Count() / model.PageSize);

            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult RenderResources(ResourceSearchModel model)
        {
            List<Resource> resources = db.Resources.ToList();

            if (model.SubjectFilters != null)
            {
                List<int> selectedSubjectsIds = model.SubjectFilters.Where(filter => filter.IsChecked)
                .Select(filter => filter.Subject.Id)
                .ToList();

                if (selectedSubjectsIds.Count > 0)
                    resources = resources.Where(resource => selectedSubjectsIds.Contains(resource.Subject.Id)).ToList();
            }

            List<int> selectedSemesters = model.SemesterFilters.Where(filter => filter.IsChecked)
                .Select(filter => (int)filter.Semester + 1)
                .ToList();

            if (selectedSemesters.Count > 0)
                resources = resources.Where(resource => selectedSemesters.Contains(resource.Subject.Semester)).ToList();

            List<int> selectedYears = model.YearFilters.Where(filter => filter.IsChecked)
                .Select(filter => (int)filter.Year + 1)
                .ToList();
            if (selectedYears.Count > 0)
                resources = resources.Where(resource => selectedYears.Contains(resource.Subject.Year)).ToList();

            if (model.StudentProgrammeFilters != null)
            {
                List<int> selectedStudyProgrammeIds = model.StudentProgrammeFilters.Where(filter => filter.IsChecked)
                .Select(filter => filter.StudyProgramme.Id)
                .ToList();
                if (selectedStudyProgrammeIds.Count > 0)
                    resources = resources.Where(resource => selectedStudyProgrammeIds.Contains(resource.Subject.StudyProgramme.Id)).ToList();
            }

            if (!String.IsNullOrEmpty(model.SearchString))
            {
                model.SearchString = model.SearchString.ToLower();
                resources = resources.Where(resource =>
                {
                    return resource.Title.ToLower().Contains(model.SearchString) ||
                    resource.Author.ToLower().Contains(model.SearchString) ||
                    resource.Subject.Name.ToLower().Contains(model.SearchString);
                }).ToList();
            }

            if (model.SelectedSortByOption == "Title")
                resources.Sort((resource1, resource2) =>
                {
                    if (model.Ascending)
                        return resource1.Title.CompareTo(resource2.Title);
                    else
                        return resource2.Title.CompareTo(resource1.Title);
                });
            else if (model.SelectedSortByOption == "Author")
                resources.Sort((resource1, resource2) =>
                {
                    if (model.Ascending)
                        return resource1.Author.CompareTo(resource2.Author);
                    else
                        return resource2.Author.CompareTo(resource1.Author);
                });
            else if (model.SelectedSortByOption == "Language")
                resources.Sort((resource1, resource2) =>
                {
                    if (model.Ascending)
                        return resource1.Language.CompareTo(resource2.Language);
                    else
                        return resource2.Language.CompareTo(resource1.Language);
                });
            else if (model.SelectedSortByOption == "Subject")
                resources.Sort((resource1, resource2) =>
                {
                    if (model.Ascending)
                        return resource1.Subject.Name.CompareTo(resource2.Subject.Name);
                    else
                        return resource2.Subject.Name.CompareTo(resource1.Subject.Name);
                });

            model.TotalPages = (int)Math.Ceiling((decimal)resources.Count / model.PageSize);

            int count = (model.PageSize < resources.Count) ? model.PageSize : resources.Count;
            model.Resources = resources.Skip(model.PageSize * (model.PageNumber - 1)).Take(count).ToList();

            if (model.Resources.Count == 0 && model.PageNumber > 0)
            {
                --model.PageNumber;
                count = (model.PageSize < resources.Count) ? model.PageSize : resources.Count;
                model.Resources = resources.Skip(model.PageSize * (model.PageNumber - 1)).Take(count).ToList();
            }

            return PartialView(model);
        }

        [AllowAnonymous]

        // GET: Resources/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resource resource = db.Resources.Find(id);
            if (resource == null)
            {
                return HttpNotFound();
            }
            return View(resource);
        }

        [Authorize(Roles = "Administrator,Teacher")]
        // GET: Resources/Create
        public ActionResult Create()
        {
            Resource resource = new Resource();
            var subjects = db.Subjects.ToList();
            subjects.Sort((subject1, subject2) => subject1.Name.CompareTo(subject2.Name));
            List<SelectListItem> list = subjects.Select(subject => new SelectListItem() { Text = subject.Name, Value = subject.Id.ToString() }).ToList();
            resource.AllSubjects = new SelectList(list, "Value", "Text");

            return View(resource);
        }

        // POST: Resources/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator,Teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Author,Description,Language,DatePublished,Notes,SubjectId,ImageURL,FileName,File")] Resource resource)
        {
            if (ModelState.IsValid)
            {
                var fileName = string.Concat(
                       Path.GetFileNameWithoutExtension(resource.File.FileName),
                       DateTime.Now.ToString("yyyyMMddHHmmssfff"),
                       Path.GetExtension(resource.File.FileName)
                   );
                var path = Path.Combine(Server.MapPath("~/App_Data/Uploads"), fileName);
                resource.File.SaveAs(path);

                resource.FileName = fileName;

                db.Resources.Add(resource);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var subjects = db.Subjects.ToList();
            subjects.Sort((subject1, subject2) => subject1.Name.CompareTo(subject2.Name));

Views/Home/Index.cshtml
@model IEnumerable<StudentELibrary.Models.Resource>

@{
    ViewBag.Title = "Почетна";
}

@section Styles {
    <style>
        @@media (max-width: 767px) {
            .carousel-inner .carousel-item > div {
                display: none;
            }

                .carousel-inner .carousel-item > div:first-child {
                    display: block;
                }
        }

        .carousel-inner .carousel-item.active,
        .carousel-inner .carousel-item-next,
        .carousel-inner .carousel-item-prev {
            display: flex;
        }

        /* medium and up screens */
        @@media (min-width: 768px) {
            .carousel-inner .carousel-item-end.active,
            .carousel-inner .carousel-item-next {
                transform: translateX(100%);
            }

            .carousel-inner .carousel-item-start.active,
            .carousel-inner .carousel-item-prev {
                transform: translateX(-100%);
            }
        }

        .carousel-inner .carousel-item-end,
        .carousel-inner .carousel-item-start {
            transform: translateX(0%);
        }

        .image-wrapper {
            height: 215px;
            width: 100%;
            margin: 0;
            padding: 0;
            left: 0;
            position: absolute;
            background-size: cover;
            background-image: url(@Url.Content("~/Content/Images/home-img.jpg"));
        }
    </style>
}

<div class="container">
    <div class="row align-items-center">
        <div class="col-lg-3">
            <figure class="my-3">
                <blockquote class="blockquote" style="font-size: larger;">
                    <p class="text-uppercase text-center text-md-start">Образованието е најмоќното оружје со коешто можеш да го промениш светот.</p>
                </blockquote>
                <figcaption class="blockquote-footer text-center text-md-start">
                    Нелсон Мандела
                </figcaption>
            </figure>
        </div>
        <div class="col-lg-9">
            <img class="img-fluid" src="~/Content/Images/main-img.jpg" />
        </div>
    </div>
    <div style="height: 215px" class="mb-5">
        <div class="image-wrapper text-center row align-content-center"><h1 class="text-uppercase text-white">Студентска е-библиотека</h1></div>
    </div>
    <div class="row">
        <div class="col">
            <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
                <div class="row align-items-center">
                    <div class="col d-flex justify-content-start">
                        <button class="ms-3 p-0 row align-items-center btn btn-outline-primary" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
                            <span class="">Previous</span>
                        </button>
                    </div>
                    <div class="col d-flex justify-content-end">
                        <button class="me-3 p-0 row align-items-center btn btn-outline-primary" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
                            <span class="">Next</span>
                        </button>
                    </div>
                </div>
                <div class="carousel-inner">
                    @foreach (var item in Model)
                    {
                        <div class="carousel-item col-12 col-md-2 col-lg-3 col-xl-4" data-bs-interval="5000">
                            <div class="row w-100">
                                <div class="col m-3 w-100">
                                    <div class="card h-100">
                                        <img src="@item.ImageURL" class="card-img-top" alt="...">
                                        <div class="card-body">
                                            <h5 class="card-title small">@item.Title</h5>
                                            <p class="card-text">
                                                @Html.ActionLink("Повеќе", "Details", "Resources", new { id = item.Id }, new { @class = "" })
                                            </p>
                                        </div>
                                        <div class="card-footer">
                                            <div class="btn-group btn-group-sm m-1" role="group">
                                                @Html.ActionLink("Преземи", "DownloadFile", "Resources", new { fileName = item.FileName, title = string.Concat(item.Title, Path.GetExtension(item.FileName)) }, new { @class = "btn btn-outline-primary shadow-none text-uppercase", style = "font-size: x-small;" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        let items = document.querySelectorAll('.carousel .carousel-item');

        $(items[0]).addClass("active");

        items.forEach((el) => {
            const minPerSlide = 4;
            let next = el.nextElementSibling;

            for (var i = 1; i < minPerSlide; i++) {
                if (!next)
                    next = items[0];

                let cloneChild = next.cloneNode(true);
                el.appendChild(cloneChild.children[0]);
                next = next.nextElementSibling;
            }
        });
    </script>
}